---
- name: Disable swap
  ansible.builtin.command: swapoff -a
  become: true

- name: Ensure swap is disabled on boot
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*\\s+swap\\s+)'
    replace: '# \\1'
  become: true

- name: Set SELinux to permissive
  ansible.posix.selinux:
    state: permissive

- name: Load br_netfilter module
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: Set sysctl parameters for Kubernetes networking
  ansible.builtin.copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1

- name: Apply sysctl settings
  ansible.builtin.command: sysctl --system

- name: Install required packages
  ansible.builtin.yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present

- name: Add Docker CE repository
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker
  ansible.builtin.yum:
    name: docker-ce
    state: present

- name: Enable and start Docker
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    state: started

- name: Add Kubernetes repo
  ansible.builtin.yum_repository:
    name: kubernetes
    description: Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: no
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg
            https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Install Kubernetes components
  ansible.builtin.yum:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    disable_gpg_check: yes

- name: Enable kubelet service
  ansible.builtin.systemd:
    name: kubelet
    enabled: yes
